### ISSUE TITLE
can't amend customer email

### ISSUE THREAD

**Issue by Cleanily** [dsahil/cleanily-issues#10]
Whilst adding customers previously some of them have made up email addresses on. I need to edit them to real ones to enable sending 'card detail requests'. I've tried deleting jobs then editing and readding job but it won't save (though doesn;t throw an error). All the customers I want to add need their email addresses changing. Also made me wonder if a customer changed their email address would their log in change?

**Comment by dsahil** [comment]
Updated, Now also added functionalty to display errors also
