### ISSUE TITLE
concept of adding 'missed' status to verification status

### ISSUE THREAD

**Issue by Cleanily** [dsahil/cleanily-issues#13]
if job end time has expired and job has not been started then it could mean that the cleaner has started and finished the job offline. However, until that data is posted from the app it should appear as missed after the job finish time has elapsed - between start and finish status should be 'not started'. If data is posted later on in the day once the cleaner gets wifi then if should auto verify to 'Verified' status. However, if this does not happen then the franchisee should be able to add a 'missed' status.

**Comment by dsahil** [comment]
between start and finish status it is live then it goes to not_started( missed is actually not_started)
