### ISSUE TITLE
Minor issue fixes

### ISSUE THREAD

**Issue by Edwardo1** [dsahil/cleanily-issues#17]
1. Remove cleaner comments from customer admin
2. Add 'Edit' and 'Delete' buttons to checklist in customer profile (thus allowing franchisee to tweak checklists - at the moment you have to log in as the customer)
3. Billing email fixes - also remove logo from email header as it distorts on mobile - see attachment
4. DOES NEED FIXING. Previous flagged items should only be visible up until the job instance has passed - also look at Kevin Maughan as an example https://cleanily.com/franchisee/customers/131. 
5. Complete totals at top of main accounts table, add lat / long, add total to bottom of table
6. Implement email for existing customers switching to new system
7. Is sign in with Google or Facebook a big job and how can I efficiently generate access details for all existing customers without individually generating a new password using update_attribute

**Comment by dsahil** [comment]
(1), (2), (3) , (5)
