### ISSUE TITLE
explainer vid pop up

### ISSUE THREAD

**Issue by Edwardo1** [dsahil/cleanily-issues#36]
![explainer-vid](https://cloud.githubusercontent.com/assets/7989420/14918359/5eb96eae-0e1b-11e6-9aff-dd5b5ae11988.jpeg)

**Comment by dsahil** [comment]
Quick Notes:
(1) Don't show it when the customer has not yet added a card and is on "accounts page"
(2) Track if the customer has already watched it and dont show it to customer again.
(3) Track if the customer has said no thanks and don't show it if the ever again.
(4) Else show it.
