### ISSUE TITLE
Scheduler row width

### ISSUE THREAD

**Issue by Edwardo1** [dsahil/cleanily-issues#55]
Likely we'll be adding at least another 10 cleaners over the course of the next 6 months so need more space on the scheduler. Something like the attachment...
![screen shot 2016-09-05 at 08 13 38](https://cloud.githubusercontent.com/assets/7989420/18239982/c5f261a4-7340-11e6-8bf8-198b1c58d293.png)

**Comment by sahild** [comment]
decrease the row wiidth and font sixe
