### ISSUE TITLE
Invoicing wireframe for the customer

### ISSUE THREAD

**Issue by dsahil** [dsahil/cleanily-issues#7]
![invice_preview](https://cloud.githubusercontent.com/assets/6213126/13287106/435c8678-db2b-11e5-8be8-cb659f416f58.png)

**Comment by Cleanily** [comment]
This one is for successful weekly payment by stripe
![stripe-weekly-invoice-payment-success](https://cloud.githubusercontent.com/assets/17448997/13300895/17f6504a-db3a-11e5-86c1-bb71500ddb4c.jpg)
This one is for a cheque/cash payment paying monthly and sent manually (print/email) by admin/franchisee
![cash-or-cheque-invoice-monthly](https://cloud.githubusercontent.com/assets/17448997/13300896/17f76502-db3a-11e5-8e21-224bee81d71e.jpg)
Stripe invoice with payment failing
![stripe-invoice-with-payment-failed](https://cloud.githubusercontent.com/assets/17448997/13300897/1808e03e-db3a-11e5-9bd0-e9f75d3d8e12.jpg)
