### ISSUE TITLE
Email content for the invoice email to the customer.

### ISSUE THREAD

**Issue by dsahil** [dsahil/cleanily-issues#8]
we will need to send an email to the customer with invoice attached as pdf.
Dear Customer,
you were charged this much , for this stuff etc etc
etc etc
Please find attached the invoice as pdf file.
You can also download your invoice from here etc etc:
    <button> cleanily.com/invoice_id </button>
From Edward

*just give me the english content , i will design a very simple email.

**Comment by Cleanily** [comment]
![billing-summary](https://cloud.githubusercontent.com/assets/17448997/13302810/cf7bc728-db43-11e5-99c9-da7052ca532c.jpg)


Text:

Hi [first_name],
Please find attached your billing summary for this week.
Billing Summary
4 Hours Regular Cleaning Service at 24 Quitealongstreetname Road £50.00
8 Hours Commercial Cleaning Services at 104 Howard Street £120.00
Total: £170.00
You can view a detailed summary by opening the PDF attached to this email.
If you are on a PC or laptop you can visit your account here to view the same information.
Thanks for your custom!
North East Manager
The Traditional Cleaning Company
Telephone
Mobile
etc
